INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES (1, 'abc@gmail.com', 'abc employee', '7878123456', 'abc');

INSERT INTO USER_ENTITY_TABLE(USER_ID, EMAIL, FULL_NAME, MOBILE_NUMBER, PASSWORD)
VALUES (2, 'xyz@gmail.com', 'xyz employee', '9898123456', 'xyz');